#! /bin/bash

#####
# Load qctool module here

QCTOOL=qctool

# (Broad institute)
# source /broad/software/scripts/useuse
# use .qctool-2.0-rc2

# (erisone.partners.org)
# module add glibc
# module add gcc/6.3.0 

# QCTOOL=~/Tools/qctool_v2.0.1/qctool_v2.0.1

#####

# SGE:
CHROM=$SGE_TASK_ID

# LSF
# CHROM=$LSB_JOBINDEX 

BGEN_PATH_BASE=$1
OUTPUT_DIR=$2

#for CHROM in `seq 1 22`; 
#do 
    echo "chrom$CHROM:"

    BGEN_PATH=`echo $BGEN_PATH_BASE | sed "s/\#/$CHROM/"`
    QCTOOL_FILE="$OUTPUT_DIR/chrom$CHROM.qctool_snpstats.txt"
    MFI_FILE="$OUTPUT_DIR/chrom$CHROM.mfi.txt"
    
    echo "    bgen input: $BGEN_PATH"

    echo "    Running qctool..."
    
    $QCTOOL -g $BGEN_PATH -osnp $QCTOOL_FILE -snp-stats

    echo "    Capturing the following columns:"
    cat $QCTOOL_FILE |grep -v "^#"  | head -n 1 | cut -d' ' -f 1-2,4-6,14,15,17 | sed 's/ /\t/g'

    echo "    SNP info output: $MFI_FILE"
    cat $QCTOOL_FILE |grep -v "^#"  | tail -n +2 | cut -d' ' -f 1-2,4-6,14,15,17 | sed 's/ /\t/g' > $MFI_FILE


    echo "    OK"

#done

echo "Done"
