###
# ADD CODES TO LOAD R MODULE HERE
# Broad institute: 
# source /broad/software/scripts/useuse
# use OpenblasR
###

# nps_decor.job
Rscript npsR/nps_decor.R $1 $SGE_TASK_ID $2 > $1/log/nps_decor.Rout.$2.$SGE_TASK_ID

logfile="$1/log/nps_decor.Rout.$2.$SGE_TASK_ID"

if [ ! -f $logfile ]; then
    echo "nps_decor FAILED: STOP"
    exit 1
fi

last=`grep -w Done $logfile | tail -n 1`

if [ "$last" != "Done" ]; then
    echo "nps_decor FAILED: STOP"
    exit 1
fi

# nps_prune.job
Rscript npsR/nps_prune.R $1 $SGE_TASK_ID $2 > $1/log/nps_prune.Rout.$2.$SGE_TASK_ID

