dir=$1
datasetName=$2
chrom=$SGE_TASK_ID

###
# ADD CODES TO LOAD MODULES HERE
#
# If you loaded a GCC module to compile stdgt, you also need to load 
# the GCC module here.

# Broad institute: 
# source /broad/software/scripts/useuse
# use GCC-5.2
###

prefix="$dir/chrom${chrom}.${datasetName}"

if [ ! -s $prefix.dosage.gz ]; then
    echo "ERROR: $prefix.dosage.gz is missing or empty"
    exit 1
fi

N=`zcat < $prefix.dosage.gz | head -n 1 | tr " " "\n" | tail -n +7 | wc -l | sed 's/^[ \t]*//'`
M=`zcat < $prefix.dosage.gz | tail -n +2 | wc -l | sed 's/^[ \t]*//'`

echo "N=$N M=$M"

zcat < $prefix.dosage.gz | ./stdgt $N $M $prefix
    
gzip -f $prefix.stdgt
    
