###
# ADD CODES TO LOAD R MODULE HERE
###

# nps_decor.job
Rscript npsR/nps_decor.R $1 $LSB_JOBINDEX $2 > $1/log/nps_decor.Rout.$2.$LSB_JOBINDEX

logfile="$1/log/nps_decor.Rout.$2.$LSB_JOBINDEX"

if [ ! -f $logfile ]; then
    echo "nps_decor FAILED: STOP"
    exit 1
fi

last=`grep -w Done $logfile | tail -n 1`

if [ "$last" != "Done" ]; then
    echo "nps_decor FAILED: STOP"
    exit 1
fi

# nps_prune.job
Rscript npsR/nps_prune.R $1 $LSB_JOBINDEX $2 > $1/log/nps_prune.Rout.$2.$LSB_JOBINDEX

