#! /bin/bash 

moddir=$1
valdir=$2
valtag=$3
winshift=$4

chrom=$LSB_JOBINDEX

###
# ADD CODES TO LOAD MODULES HERE
#
# Load R module if necessary. 
# 
# If you loaded a GCC module to compile grs, you also need to load 
# the GCC module here. 
# 
###

traintag=`Rscript -e "args <- readRDS(\"$moddir/args.RDS\"); cat(\":NPS:\\t\", args[[\"traintag\"]], sep='');" | grep -F ':NPS:' | cut -f2 `

modtag="$traintag.win_${winshift}"

prefix="$valdir/chrom${chrom}.${valtag}"

if [ ! -s "$prefix.dosage.gz" ]; then
    echo "ERROR: $prefix.dosage.gz is missing or empty"
    exit 1
fi

M=`zcat < $prefix.dosage.gz | tail -n +2 | wc -l | cut -d' ' -f1`
N=`zcat < $prefix.dosage.gz | head -n 1 | tr " " "\n" | tail -n +7 | wc -l`

echo "chr$chrom N=$N M=$M"

zcat < $prefix.dosage.gz | ./grs $N $M $moddir/$modtag.adjbetahat.chrom$chrom.txt > $moddir/$modtag.predY.$valtag.chrom$chrom.sscore
